[package]
name = "kd-tree"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
lto = true
panic = 'abort'
codegen-units = 1

[dependencies]
rand = "0.8.5"
plotters = "0.3.5"
apng = "0.3.1"
png = "0.17.9"
image = { version = "0.24.6", default-features = false, features = ["png"] }